# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestYoutubeviewcount():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_youtubeviewcount(self):
    self.driver.get("https://www.youtube.com/watch?v=mspbVxNxO7M")
    self.vars["vc"] = self.driver.find_element(By.CSS_SELECTOR, ".view-count").text
    print(str(self.vars["vc"]))
  
